### ISSUE TITLE
Does not work with Codeception 5

### ISSUE THREAD

**Issue by boboldehampsink** [Codeception/module-yii2#71]
Latest release should be able to work with Codeception 5, but fails:

```


Functional Tests (39) ----------------------------------------------------------
--
  | - BlogCest: Test blog \| "/blog/blog-title-1","Blog Title 1"--------------------------------------------------------------------------------
  | <pre>Exception 'Error' with message 'Call to undefined method Codeception\Test\Cest::getTestClass()'
  |  
  | in /app/user/vendor/codeception/module-yii2/src/Codeception/Module/Yii2.php:336
  |  
  | Stack trace:
  | #0 /app/user/vendor/craftcms/cms/src/test/Craft.php(165): Codeception\Module\Yii2-&gt;_before(Object(Codeception\Test\Cest))
  | #1 /app/user/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php(69): craft\test\Craft-&gt;_before(Object(Codeception\Test\Cest))
  | #2 /app/user/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Codeception\Subscriber\Module-&gt;before(Object(Codeception\Event\TestEvent), 'test.before', Object(Symfony\Component\EventDispatcher\EventDispatcher))
  | #3 /app/user/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher-&gt;callListeners(Array, 'test.before', Object(Codeception\Event\TestEvent))
  | #4 /app/user/vendor/codeception/codeception/src/Codeception/Test/Test.php(275): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch(Object(Codeception\Event\TestEvent), 'test.before')
  | #5 /app/user/vendor/codeception/codeception/src/Codeception/Test/Test.php(151): Codeception\Test\Test-&gt;fire('test.before', Object(Codeception\Event\TestEvent))
  | #6 /app/user/vendor/codeception/codeception/src/Codeception/Suite.php(132): Codeception\Test\Test-&gt;realRun(Object(Codeception\ResultAggregator))
  | #7 /app/user/vendor/codeception/codeception/src/Codeception/SuiteManager.php(148): Codeception\Suite-&gt;run(Object(Codeception\ResultAggregator))
  | #8 /app/user/vendor/codeception/codeception/src/Codeception/Codecept.php(260): Codeception\SuiteManager-&gt;run(Object(Codeception\ResultAggregator))
  | #9 /app/user/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept-&gt;runSuite(Array, 'functional', NULL)
  | #10 /app/user/vendor/codeception/codeception/src/Codeception/Command/Run.php(655): Codeception\Codecept-&gt;run('functional')
  | #11 /app/user/vendor/codeception/codeception/src/Codeception/Command/Run.php(476): Codeception\Command\Run-&gt;runSuites(Array, Array)
  | #12 /app/user/vendor/symfony/console/Command/Command.php(298): Codeception\Command\Run-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #13 /app/user/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #14 /app/user/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #15 /app/user/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #16 /app/user/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  | #17 /app/user/vendor/codeception/codeception/app.php(45): Codeception\Application-&gt;run()
  | #18 /app/user/vendor/codeception/codeception/app.php(46): {closure}()
  | #19 /app/user/vendor/codeception/codeception/codecept(7): require('/app/user/vendo...')
  | #20 /app/user/vendor/bin/codecept(120): include('/app/user/vendo...')
  | #21 {main}</pre>


```

**Comment by Naktibalda** [comment]
Thanks, fixed in 1.1.7
